basePath: /api/v1
definitions:
  go-simple-rest_src_v1_authors_model.Author:
    properties:
      createdAt:
        type: string
      firstName:
        type: string
      id: {}
      lastName:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  go-simple-rest_src_v1_authors_model.AuthorArticle:
    properties:
      authorId:
        type: string
      categories:
        items:
          type: string
        type: array
      content:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id: {}
      likes:
        type: integer
      status:
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updatedAt:
        type: string
      views:
        type: integer
    type: object
  model.Article:
    properties:
      authorId:
        type: string
      categories:
        items:
          type: string
        type: array
      content:
        type: string
      createdAt:
        type: string
      createdAtTimestamp:
        type: integer
      deletedAt:
        type: string
      deletedAtTimestamp:
        type: integer
      id: {}
      likes:
        type: integer
      status:
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updatedAt:
        type: string
      updatedAtTimestamp:
        type: integer
      views:
        type: integer
    type: object
  model.AuthorArticleUpdateRequest:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  model.AuthorArticleUpdateResponse:
    properties:
      message:
        type: string
    type: object
  model.LoginAuth:
    properties:
      password:
        description: password
        minLength: 4
        type: string
      username:
        description: username
        minLength: 1
        type: string
    required:
    - password
    - username
    type: object
  model.LoginResponse:
    properties:
      message:
        type: string
      token:
        type: string
      user:
        $ref: '#/definitions/model.UserResponseObject'
    type: object
  model.RegisterAuth:
    properties:
      firstname:
        type: string
      lastname:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - firstname
    - lastname
    - password
    - username
    type: object
  model.UserResponseObject:
    properties:
      id:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: 127.0.0.1:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /articles:
    get:
      description: Retrieves articles
      parameters:
      - description: Sort by date
        example: '"desc"'
        in: query
        name: date
        type: string
      - description: Sort by likes
        example: '"desc"'
        in: query
        name: likes
        type: string
      - description: Sort by views
        in: query
        name: views
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            items:
              $ref: '#/definitions/model.Article'
            type: array
        "400":
          description: Error
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Get articles
      tags:
      - Articles
  /articles/{id}:
    get:
      description: Retrieves a specific article by ID.
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/model.Article'
        "400":
          description: Error
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Get articles by id
      tags:
      - Articles
    put:
      description: Updates a specific article by ID.
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            type: string
        "400":
          description: Error
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Update articles by id
      tags:
      - Articles
  /articles/{id}/comments:
    get:
      description: Retrieves comments for a specific article.
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Prev
        in: query
        name: prev
        required: true
        type: integer
      - description: Next
        in: query
        name: next
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            type: string
        "400":
          description: Error
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Get article comments
      tags:
      - Articles
  /articles/{id}/comments/{cid}/reply:
    post:
      description: Replies to a specific comment.
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: string
      - description: Comment ID
        in: path
        name: cid
        required: true
        type: string
      - description: Content
        in: body
        name: content
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            type: string
        "400":
          description: Error
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Reply to a comment
      tags:
      - Articles
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login user with username and password
      parameters:
      - description: User
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.LoginAuth'
      produces:
      - application/json
      responses:
        "200":
          description: Response
          headers:
            Cookie:
              description: session_id
              type: string
          schema:
            $ref: '#/definitions/model.LoginResponse'
        "400":
          description: Error
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Login user
      tags:
      - User Authentication
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Register user with username,password, firstname and lastname
      parameters:
      - description: User
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.RegisterAuth'
      produces:
      - application/json
      responses:
        "201":
          description: Response
          schema:
            type: string
        "400":
          description: Error
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Register user
      tags:
      - User Authentication
  /authors/{id}:
    delete:
      description: Deletes an author
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Delete a specific author
      tags:
      - Authors
    get:
      description: Retrieves a specific author by ID.
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/go-simple-rest_src_v1_authors_model.Author'
        "400":
          description: Error
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Get author by id
      tags:
      - Authors
    put:
      description: Updates an author
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            type: string
        "422":
          description: Response
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Update a specific author
      tags:
      - Authors
  /authors/{id}/articles:
    get:
      description: Retrieves all articles written by a specific author.
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            type: string
        "400":
          description: Error
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Get all articles by author
      tags:
      - Authors
    post:
      description: Creates a new article written by a specific author.
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      - description: Article
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/go-simple-rest_src_v1_authors_model.AuthorArticle'
      produces:
      - application/json
      responses:
        "201":
          description: Response
          schema:
            type: string
        "400":
          description: Error
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Create a new article written by a specific author
      tags:
      - Authors
  /authors/{id}/articles/{articleId}:
    delete:
      description: Deletes an article written by a specific author.
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      - description: Article ID
        in: path
        name: articleId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/model.AuthorArticleUpdateResponse'
        "400":
          description: Error
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Delete an article written by a specific author
      tags:
      - Authors
    put:
      description: Updates an article written by a specific author.
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      - description: Article ID
        in: path
        name: articleId
        required: true
        type: string
      - description: Article
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.AuthorArticleUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/model.AuthorArticleUpdateResponse'
        "400":
          description: Error
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Update an article written by a specific author
      tags:
      - Authors
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
